export const ROUTER = {
  BASE: 'api',
  ADMIN: {
    LOGIN: 'login',
    SESSION: 'session',
    REFRESH: 'refresh',
    ANALYTICS: {
      GMV: 'gmv',
      GMV_CHART: 'gmv/chart',
      GMV_FORECAST: 'gmv/forecast',
      SERVICE_FEE: 'service-fee',
      SERVICE_FEE_CHART: 'service-fee/chart',
      SERVICE_FEE_FORECAST: 'service-fee/forecast',
      CR: 'cr',
      CR_CHART: 'cr/chart',
      CR_FORECAST: 'cr/forecast',
      AVERAGE_CONFIRMATION_TIME: 'average-confirmation-time',
      AVERAGE_CONFIRMATION_TIME_CHART: 'average-confirmation-time/chart',
      AVERAGE_CONFIRMATION_TIME_FORECAST: 'average-confirmation-time/forecast',
      P95_CONFIRMATION_TIME: 'p95-confirmation-time',
      P95_CONFIRMATION_TIME_CHART: 'p95-confirmation-time/chart',
      P95_CONFIRMATION_TIME_FORECAST: 'p95-confirmation-time/forecast',
      DIRECT_DEPOSIT_SHARE: 'direct-deposit-share',
      DIRECT_DEPOSIT_SHARE_CHART: 'direct-deposit-share/chart',
      DIRECT_DEPOSIT_SHARE_FORECAST: 'direct-deposit-share/forecast',
      SLOWEST_TRANSACTIONS: 'slowest-transactions',
      FAILURE_SHARE: 'failure-share',
      FAILURE_SHARE_CHART: 'failure-share/chart',
      FAILURE_SHARE_FORECAST: 'failure-share/forecast',
      ALERTS: 'alerts',
      ACTIVE_MERCHANTS: 'active-merchants',
      ACTIVE_MERCHANTS_CHART: 'active-merchants/chart',
      ACTIVE_MERCHANTS_FORECAST: 'active-merchants/forecast',
      NEW_MERCHANTS: 'new-merchants',
      NEW_MERCHANTS_HEATMAP: 'new-merchants/heatmap',
      MERCHANT_RETENTION: 'merchant-retention',
      HOTSPOTS: 'hotspots',
    },
  },
  AUTH: {
    LOGIN: 'login',
    REGISTER: 'register',
    REFRESH: 'refresh',
    SESSION: 'session',
  },
  USER: {
    UPDATE_PASSWORD: 'password',
  },
  MERCHANT: {
    CREATE: '',
    GET_ALL: '',
    GET_ONE: ':id',
    UPDATE: ':id',
    DELETE: ':id',
    COLLECT_ADDRESSES: ':id/collect-addresses',
    WITHDRAW: ':id/withdraw',
    ANALYTICS: {
      GMV: ':id/gmv',
      GMV_CHART: ':id/gmv/chart',
      GMV_FORECAST: ':id/gmv/forecast',
      SERVICE_FEE: ':id/service-fee',
      SERVICE_FEE_CHART: ':id/service-fee/chart',
      SERVICE_FEE_FORECAST: ':id/service-fee/forecast',
      CR: ':id/cr',
      CR_CHART: ':id/cr/chart',
      CR_FORECAST: ':id/cr/forecast',
      AVERAGE_CONFIRMATION_TIME: ':id/average-confirmation-time',
      AVERAGE_CONFIRMATION_TIME_CHART: ':id/average-confirmation-time/chart',
      AVERAGE_CONFIRMATION_TIME_FORECAST:
        ':id/average-confirmation-time/forecast',
      P95_CONFIRMATION_TIME: ':id/p95-confirmation-time',
      P95_CONFIRMATION_TIME_CHART: ':id/p95-confirmation-time/chart',
      P95_CONFIRMATION_TIME_FORECAST: ':id/p95-confirmation-time/forecast',
      DIRECT_DEPOSIT_SHARE: ':id/direct-deposit-share',
      DIRECT_DEPOSIT_SHARE_CHART: ':id/direct-deposit-share/chart',
      DIRECT_DEPOSIT_SHARE_FORECAST: ':id/direct-deposit-share/forecast',
      AOV: ':id/aov',
      AOV_CHART: ':id/aov/chart',
      AOV_FORECAST: ':id/aov/forecast',
      REPEAT_CUSTOMER_RATE: ':id/repeat-customer-rate',
      REPEAT_CUSTOMER_RATE_CHART: ':id/repeat-customer-rate/chart',
      REPEAT_CUSTOMER_RATE_FORECAST: ':id/repeat-customer-rate/forecast',
      FUNNEL_CHART: ':id/funnel',
      HOURLY_HEATMAP: ':id/hourly-heatmap',
      SLOWEST_TRANSACTIONS: ':id/slowest-transactions',
      ALERTS: ':id/alerts',
      FAILURE_SHARE: ':id/failure-share',
      FAILURE_SHARE_CHART: ':id/failure-share/chart',
      FAILURE_SHARE_FORECAST: ':id/failure-share/forecast',
    },
  },
  TRANSACTION: {
    GET_ALL: '',
    GET_ONE: ':id',
  },
  API_KEY: {
    CREATE: '',
    GET_ALL: '',
    GET_ONE: ':id',
    DELETE: ':id',
  },
  ADDRESS: {
    CREATE: '',
  },
  WEBHOOK: 'webhook',
};
